version: '3.9'

services:
  db:
      container_name: postgres
      image: postgres:16
      environment:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_DB: $POSTGRES_DB
      ports:
        - 5434:5432
      volumes:
        - db_data:/var/lib/postgresql/data

  web:
    environment:
      DB_HOST: $DB_URL
      FLASK_APP: runserver.py
    container_name: web
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db


volumes:
  db_data:
