version: '3.9'

services:
  db:
      container_name: postgres
      image: postgres:16
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: avkr17
      ports:
        - 5434:5432
      volumes:
        - db_data:/var/lib/postgresql/data

  web:
    environment:
      DB_HOST: postgresql://postgres:postgres@postgres/avkr17
      FLASK_APP: runserver.py
    container_name: web
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db


volumes:
  db_data:
